######################################################################
# Automatically generated by qmake (2.01a) Wed May 18 08:43:26 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += http.h
SOURCES += http.cpp main.cpp
