######################################################################
# Automatically generated by qmake (2.01a) Tue May 17 23:45:13 2011
######################################################################

TEMPLATE = lib
TARGET = httphelper
DSTDIR = ./lib
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += PostParameter.cpp Response.cpp BasicAuthorization.cpp
