######################################################################
# Automatically generated by qmake (2.01a) Wed May 18 00:14:50 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
